accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/create_com/', views.create_com, name='create_com'),
    # /articles/3/create_com/5/delete/
    path('<int:article_pk>/create_com/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models
from django.core.validators import EmailValidator, MinValueValidator
from django.conf import settings

# Create your models here.
# article.liked_users.all()
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    content2 = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # article.user => article 입장에서
    # comment.article
    # article.comment_set.all()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users')  # models.py 에서만 이렇게 가져오고 나머지는 form.py 문법을 통해 가져온다. => django 실행 순서와 관련있다.
    liked_users = models.ManyToManyField( # article.liked_users.all() => 아티클을 좋아하는 모든 유저
        settings.AUTH_USER_MODEL,
        related_name='liked_articles', # user.liked_articles.all() => 유저가 좋아하는 모든 아티클
    )


    class Meta:
        ordering = ('-pk', )

class Person(models.Model):
    name = models.CharField(max_length=10)
    email = models.CharField(
        max_length=100,
        validators=[EmailValidator(message='이메일 형식에 맞지 않습니다.')]

    )
    age = models.IntegerField(
        validators=[MinValueValidator(19, message='미성년자는 노노')]
    )


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    

    class Meta:
        ordering = ('-pk', )

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        # fields = ['title', ...]
        fields = ['title', 'content', ]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm



@require_GET  
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


@require_GET
def detail(request, article_pk):
    # 사용자가 url 에 적어보낸 article_pk 를 통해 디테일 페이지를 보여준다.
    # Article.objects.get(pk=article_pk) => 방법1
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm()
    comments = article.comments.all()
    context = {'article': article, 'form': form, 'comments': comments}
    return render(request, 'articles/detail.html', context)
    

@login_required  # ==> /accounts/login/  으로 보내줌, 만약 url을 다른 방식으로 설정했으면 쟝고 세팅을 바꿔줘야함 @login_required(login_url='/accounts/login/')
# GET 요청으로 사용되는 곳만 사용할 수 있다.
# Create your views here.
def create(request):
    if request.method == 'POST':
        # Article 을 생성해달라고 하는 요청
        form = ArticleForm(request.POST)
        if form.is_valid():  # 유효성 검사
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)

    else: # GET
        # Article 을 생성하기 위한 페이지를 달라고 하는 요청
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else:  # GET method
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:detail', article_pk)
    context = {'form': form}
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, article_pk):
    
    if request.user.is_authenticated:

        # article_pk에 맞는 article 을 꺼낸다.
        # 삭제한다.
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')


@require_POST
def create_com(request, article_pk):
    if request.user.is_authenticated:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # 데이터베이스에는 적용시키지 마라
            comment.article_id = article_pk
            comment.user = request.user
            form.save()
    return redirect('articles:detail', article_pk)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
        return redirect('articles:detail', article_pk)
    return HttpResponse('You are Unauthorized', status=401)


def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)
    if article.liked_users.filter(pk=user.pk).exists():
        user.liked_articles.remove(article)
    else:
        user.liked_articles.add(article)

    return redirect('articles:detail', article_pk)


def follow(request, article_pk, user_pk):
    # 로그인한 유저가 게시글 유저를 Follow or Unfollow 한다.
    user = request.user  # 로그인 유저
    person = get_object_or_404(get_user_model(), pk=user_pk)  # 게시글 주인

    if user in person.followers.all():  # 이미 팔로우
        person.followers.remove(user) # 언팔하겠음
    else:
        person.followers.add(user)

    return redirect('articles:detail', article_pk   )

articles/templates/articles/_follow.html
  <div class="jumbotron text-center text-white bg-dark">
      <p class="lead mb-1">작성자 정보</p>
      <h1 class="display-4">{{ article.user.username }}</h1>
      <hr>
      <p class="lead">
        팔로잉 : {{ article.user.followings.all | length }}/
        팔로워 : {{ article.user.followers.all | length }}
      </p>
      {% if user in article.user.followers.all %}
        <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Unfollow</a>
        
      {% else %}
        <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Follow</a>
      {% endif %}
  </div>

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %} Article::Create{% endblock title %}

{% block container %}

<form method="post"> 
  {% csrf_token %}
  {% comment %} action url이 현재 url이 동일하면 생략하기도 한다. {% endcomment %}
  
  {{ form.as_p }}
  <button type="submit">생성하기</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article:Detail{% endblock title %}

{% block container %}

<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>작성자: {{ article.user }}</p>
<hr>
<p>{{ article.content }}</p>
<a href="{% url 'articles:like' article.pk %}">
  {% if user in article.liked_users.all %}
    <i class="fas fa-heart fa-lg" style="color: red"></i>

  {% else %}
    <i class="far fa-heart fa-lg" style="color: red"></i>

  {% endif %}
</a>
<span>{{ article.liked_users.all | length }} 명이 이 글을 좋아합니다.</span>

<a href=""></a>
<br>

{% if article.user == request.user %}
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="post">
    {% csrf_token %}
    <button type="submit">[삭제하기]</button>
  </form>
{% endif %}

<br>
<hr>
<br>

<h3>Comment</h3>

{% if user.is_authenticated %}
<form action="{% url 'articles:create_com' article.pk %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">[작성하기]</button>
</form>
{% endif %}
<ul>
{% for comment in comments %}
  
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="post">
      {% csrf_token %}
      <span>{{ comment.content }} - {{ comment.created_at }} - {{ comment.user }}</span>
      {% if comment.user == request.user %}
      <button type="submit">[삭제]</button>
      {% endif %}
    </form>
    

  
{% endfor %}
</ul>

{% include 'articles/_follow.html' %}

{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Article:index{% endblock title %}

{% block container %}
  <h2>Article List</h2>
  {% comment %} GET 요청 {% endcomment %}
  {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">생성하기</a>
  {% else %}
    <a href="">생성하기</a>
    <br>
    <p>글을 작성하기 위해 <a href="{% url 'accounts:login' %}">로그인</a> 이 필요합니다.</p> 
  {% endif %}
  
  <hr>
  {% for article in articles %}
    <div>
      <h3>{{ article.pk }}. {{ article.title }}</h3>
      <p>작성자: {{ article.user }}</p>
      <a href="{% url 'articles:detail' article.pk %}">[상세보기]</a>
    </div>
    <br>
  {% endfor %}

{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %} Article::Create{% endblock title %}

{% block container %}

<form method="post"> 
  {% csrf_token %}
  {% comment %} action url이 현재 url이 동일하면 생략하기도 한다. {% endcomment %}
  
  {{ form.as_p }}
  <button type="submit">수정하기</button>
</form>
{% endblock container %}