accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/create_com/', views.create_com, name='create_com'),
    # /articles/3/create_com/5/delete/
    path('<int:article_pk>/create_com/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  
  <!doctype html>
  <html>
    <head>
      <!-- Place your kit's code here -->
      <script src="https://kit.fontawesome.com/f0508c926b.js" crossorigin="anonymous"></script>
    </head>

    <body>
      <!-- Ready to use Font Awesome. Activate interlock. Dynotherms - connected. Infracells - up. Icons are go! -->
    </body>
  </html>

  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">
  <header>
    <h1>저희 페이지 오신걸 환영합니다.</h1>
    
      {% if user.is_authenticated %}
      <p>
        <span>Hello, {{ user.username }}</span>
        <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
        <a href="{% url 'accounts:update' %}">[회원정보 수정]</a>
        <form action="{% url 'accounts:delete' %}">
         {% csrf_token %}
         <button type="submit">회원탈퇴</button>
        </form>
      </p>
      {% else %}
        <p>
        <a href="{% url 'accounts:login' %}">[로그인]</a>
        <a href="{% url 'accounts:signup' %}">[회원가입]</a>
        </p>
      {% endif %}
      
      
    </p>
  </header>

  <a href="{% url 'articles:index' %}">[목록]</a>
  {% block container %}

  
  <div class="jumbotron text-center text-white bg-dark">
  

  </div>

  <script src="http://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  {% endblock container %}
  </div>
</body>
</html>